spring:
  jackson:
    default-property-inclusion: non_null

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/medicine?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false

  jpa:
    show-sql: true


#    hibernate:
#      ddl-auto: update
#server:
#  context-path: /sell


